"""Add status field to assistants

Revision ID: f2a52438efd7
Revises: 
Create Date: 2026-04-21 17:03:35.982764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2a52438efd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='Assistant status (0: pending review, 1: active/approved, other values for specific states)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'status')
    # ### end Alembic commands ###
